### ISSUE TITLE
Whoops, typo in my pull request

### ISSUE THREAD

**Issue by Lelectrolux** [martin-c91/laratwit#11]
[Should be `$users` not `$user`.](https://github.com/martin-c91/laratwit/blob/5cf4950de89d5cb28ff9c901e00a9e768f808e13/app/User.php#L131)

```php
return $this->followings()->whereIn('user_id', $users)->exists();
```

TBH I free coded all pull requests from inside github, so I had no autocomplete/syntax higlighting/help from an IDE.

Expect 1 or 2 typos, sry.

**Comment by martin-c91** [comment]
Cool thanks.
